### PR TITLE
Students trapped in tutorial form and intro text not shown to student…

### LINKED ISSUE #311: Students trapped in tutorial form and intro text not shown to students.
When the setting 'Show an offline quiz tutorial to students.' is on and `empty($offlinequiz->time) && $offlinequiz->time < time()` , the activity redirects the students to 'tutorial.php', bypassing the intro page. Moreover, once in tutorial.php the student can't return to intro page.

Steps to reproduce:
1) Activate 'Show an offline quiz tutorial to students' setting in a offlinequiz instance.
2) Don't set a due time or set a future time.
3) Login as student.

Desired behaviour:
* When the offlinequiz is not finished (or has no due date) the students should view intro text. It would be very useful to show the student identification to be used in the answering forms.
* If the setting 'Show an offline quiz tutorial to students' is on, a link with an invitation to the tutorial should be shown.

PD: This behaviour was working in previous versions.

### PR DESCRIPTION
**Pull request by juacas**
This pull request modifies the behavior of the `view.php` file in the `offlinequiz` module to enhance the user experience by displaying the student's identification number and providing a button to start the tutorial instead of redirecting immediately.

### Changes to user interface and behavior:
* Replaced the immediate redirect to the tutorial page with a more user-friendly interface that displays the student's identification number and a button to start the tutorial. This change improves clarity and allows users to know their identifier before proceeding the offlinequiz. Fix #311

### CODE REVIEW

File: view.php [hunk 1]
```diff
@@ -467,7 +467,18 @@
     } else if ($offlinequiz->showtutorial) {
         $url = new moodle_url($CFG->wwwroot . '/mod/offlinequiz/tutorial.php',
             array('id' => $cm->id));
-        redirect($url);
+        echo $OUTPUT->header();
```
Comment (juacas) [inline view.php:470]: This code was retrieved from previous versions of offlinequiz. I liked it to much. Its easy to use and non-intrusive.
At fisrt I thought of forcing the student to do the tutorial, but then I throught that the first time it will be valueable but a pain in the ass after a full semester of exams. Moreover, for the student the description text and the USERID are the most important information pieces of the offlinequiz activity before the exam itselt.
